package Producto;


/**
* Producto/Productos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Producto.idl
* domingo 18 de noviembre de 2018 01H57' COT
*/

public interface Productos extends ProductosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Productos
