package Producto;


/**
* Producto/ProductosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Producto.idl
* domingo 18 de noviembre de 2018 01H57' COT
*/

public interface ProductosOperations 
{
  boolean insertarProducto (String Nombre, float Precio);
  boolean actualizarProducto (int id_producto, String Nombre, float Precio);
  boolean eliminarProducto (int id_producto);
  String consultarProducto (int id_producto);
  void shoutdown ();
} // interface ProductosOperations
