package Producto;

/**
* Producto/ProductosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Producto.idl
* domingo 18 de noviembre de 2018 01H57' COT
*/

public final class ProductosHolder implements org.omg.CORBA.portable.Streamable
{
  public Producto.Productos value = null;

  public ProductosHolder ()
  {
  }

  public ProductosHolder (Producto.Productos initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Producto.ProductosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Producto.ProductosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Producto.ProductosHelper.type ();
  }

}
