package Producto;


/**
* Producto/ProductosPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Producto.idl
* domingo 18 de noviembre de 2018 01H57' COT
*/

public abstract class ProductosPOA extends org.omg.PortableServer.Servant
 implements Producto.ProductosOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarProducto", new java.lang.Integer (0));
    _methods.put ("actualizarProducto", new java.lang.Integer (1));
    _methods.put ("eliminarProducto", new java.lang.Integer (2));
    _methods.put ("consultarProducto", new java.lang.Integer (3));
    _methods.put ("shoutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Producto/Productos/insertarProducto
       {
         String Nombre = in.read_wstring ();
         float Precio = in.read_float ();
         boolean $result = false;
         $result = this.insertarProducto (Nombre, Precio);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Producto/Productos/actualizarProducto
       {
         int id_producto = in.read_long ();
         String Nombre = in.read_wstring ();
         float Precio = in.read_float ();
         boolean $result = false;
         $result = this.actualizarProducto (id_producto, Nombre, Precio);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Producto/Productos/eliminarProducto
       {
         int id_producto = in.read_long ();
         boolean $result = false;
         $result = this.eliminarProducto (id_producto);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Producto/Productos/consultarProducto
       {
         int id_producto = in.read_long ();
         String $result = null;
         $result = this.consultarProducto (id_producto);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // Producto/Productos/shoutdown
       {
         this.shoutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Producto/Productos:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Productos _this() 
  {
    return ProductosHelper.narrow(
    super._this_object());
  }

  public Productos _this(org.omg.CORBA.ORB orb) 
  {
    return ProductosHelper.narrow(
    super._this_object(orb));
  }


} // class ProductosPOA
