package Vendedores;


/**
* Vendedores/VendedorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Vendedor.idl
* domingo 18 de noviembre de 2018 04H00' COT
*/

public abstract class VendedorPOA extends org.omg.PortableServer.Servant
 implements Vendedores.VendedorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarVendedor", new java.lang.Integer (0));
    _methods.put ("actualizarVendedor", new java.lang.Integer (1));
    _methods.put ("eliminarVendedor", new java.lang.Integer (2));
    _methods.put ("consultarVendedor", new java.lang.Integer (3));
    _methods.put ("shoutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Vendedores/Vendedor/insertarVendedor
       {
         String Nombre = in.read_wstring ();
         int Telefono = in.read_long ();
         int Cedula = in.read_long ();
         String Cargo = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarVendedor (Nombre, Telefono, Cedula, Cargo);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Vendedores/Vendedor/actualizarVendedor
       {
         int id_vendedor = in.read_long ();
         String Nombre = in.read_wstring ();
         int Telefono = in.read_long ();
         int Cedula = in.read_long ();
         String Cargo = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarVendedor (id_vendedor, Nombre, Telefono, Cedula, Cargo);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Vendedores/Vendedor/eliminarVendedor
       {
         int id_vendedor = in.read_long ();
         boolean $result = false;
         $result = this.eliminarVendedor (id_vendedor);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Vendedores/Vendedor/consultarVendedor
       {
         int id_vendedor = in.read_long ();
         String $result = null;
         $result = this.consultarVendedor (id_vendedor);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // Vendedores/Vendedor/shoutdown
       {
         this.shoutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Vendedores/Vendedor:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Vendedor _this() 
  {
    return VendedorHelper.narrow(
    super._this_object());
  }

  public Vendedor _this(org.omg.CORBA.ORB orb) 
  {
    return VendedorHelper.narrow(
    super._this_object(orb));
  }


} // class VendedorPOA
