package Vendedores;


/**
* Vendedores/VendedorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Vendedor.idl
* domingo 18 de noviembre de 2018 04H00' COT
*/

abstract public class VendedorHelper
{
  private static String  _id = "IDL:Vendedores/Vendedor:1.0";

  public static void insert (org.omg.CORBA.Any a, Vendedores.Vendedor that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Vendedores.Vendedor extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Vendedores.VendedorHelper.id (), "Vendedor");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Vendedores.Vendedor read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_VendedorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Vendedores.Vendedor value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Vendedores.Vendedor narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Vendedores.Vendedor)
      return (Vendedores.Vendedor)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Vendedores._VendedorStub stub = new Vendedores._VendedorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Vendedores.Vendedor unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Vendedores.Vendedor)
      return (Vendedores.Vendedor)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Vendedores._VendedorStub stub = new Vendedores._VendedorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
