package Domicilio;


/**
* Domicilio/DomiciliosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Domicilio.idl
* sábado 17 de noviembre de 2018 10H51' COT
*/

public interface DomiciliosOperations 
{
  boolean insertarDomicilio (String Nombre, String Telefono, String Cedula);
  boolean actualizarDomicilio (int id_domiciliario, String Nombre, String Telefono, String Cedula);
  boolean eliminarDomicilio (int id_domiciliario);
  String consultarDomicilio (int id_domiciliario);
  void shoutdown ();
} // interface DomiciliosOperations
