package Domicilio;


/**
* Domicilio/Domicilios.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Domicilio.idl
* sábado 17 de noviembre de 2018 10H51' COT
*/

public interface Domicilios extends DomiciliosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Domicilios
