package Domicilio;

/**
* Domicilio/DomiciliosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Domicilio.idl
* sábado 17 de noviembre de 2018 10H51' COT
*/

public final class DomiciliosHolder implements org.omg.CORBA.portable.Streamable
{
  public Domicilio.Domicilios value = null;

  public DomiciliosHolder ()
  {
  }

  public DomiciliosHolder (Domicilio.Domicilios initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Domicilio.DomiciliosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Domicilio.DomiciliosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Domicilio.DomiciliosHelper.type ();
  }

}
