package Domicilio;


/**
* Domicilio/DomiciliosPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Domicilio.idl
* sábado 17 de noviembre de 2018 10H51' COT
*/

public abstract class DomiciliosPOA extends org.omg.PortableServer.Servant
 implements Domicilio.DomiciliosOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarDomicilio", new java.lang.Integer (0));
    _methods.put ("actualizarDomicilio", new java.lang.Integer (1));
    _methods.put ("eliminarDomicilio", new java.lang.Integer (2));
    _methods.put ("consultarDomicilio", new java.lang.Integer (3));
    _methods.put ("shoutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Domicilio/Domicilios/insertarDomicilio
       {
         String Nombre = in.read_wstring ();
         String Telefono = in.read_wstring ();
         String Cedula = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarDomicilio (Nombre, Telefono, Cedula);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Domicilio/Domicilios/actualizarDomicilio
       {
         int id_domiciliario = in.read_long ();
         String Nombre = in.read_wstring ();
         String Telefono = in.read_wstring ();
         String Cedula = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarDomicilio (id_domiciliario, Nombre, Telefono, Cedula);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Domicilio/Domicilios/eliminarDomicilio
       {
         int id_domiciliario = in.read_long ();
         boolean $result = false;
         $result = this.eliminarDomicilio (id_domiciliario);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Domicilio/Domicilios/consultarDomicilio
       {
         int id_domiciliario = in.read_long ();
         String $result = null;
         $result = this.consultarDomicilio (id_domiciliario);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // Domicilio/Domicilios/shoutdown
       {
         this.shoutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Domicilio/Domicilios:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Domicilios _this() 
  {
    return DomiciliosHelper.narrow(
    super._this_object());
  }

  public Domicilios _this(org.omg.CORBA.ORB orb) 
  {
    return DomiciliosHelper.narrow(
    super._this_object(orb));
  }


} // class DomiciliosPOA
