package Domicilio;


/**
* Domicilio/DomiciliosHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Domicilio.idl
* sábado 17 de noviembre de 2018 10H51' COT
*/

abstract public class DomiciliosHelper
{
  private static String  _id = "IDL:Domicilio/Domicilios:1.0";

  public static void insert (org.omg.CORBA.Any a, Domicilio.Domicilios that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Domicilio.Domicilios extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Domicilio.DomiciliosHelper.id (), "Domicilios");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Domicilio.Domicilios read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DomiciliosStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Domicilio.Domicilios value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Domicilio.Domicilios narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Domicilio.Domicilios)
      return (Domicilio.Domicilios)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Domicilio._DomiciliosStub stub = new Domicilio._DomiciliosStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Domicilio.Domicilios unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Domicilio.Domicilios)
      return (Domicilio.Domicilios)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Domicilio._DomiciliosStub stub = new Domicilio._DomiciliosStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
