package Clientes;


/**
* Clientes/ClienteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Vehiculo.idl
* domingo 18 de noviembre de 2018 02H38' COT
*/

public interface ClienteOperations 
{
  boolean insertarCliente (String Nombre, String Apellido, int Edad);
  boolean actualizarCliente (int id_cliente, String Nombre, String Apellido, int Edad);
  boolean eliminarCliente (int id_cliente);
  String consultarCliente (int id_cliente);
  void shoutdown ();
} // interface ClienteOperations
