package Cliente;


/**
* Cliente/ClientesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cliente.idl
* viernes 16 de noviembre de 2018 21H54' COT
*/

public interface ClientesOperations 
{
  boolean insertarCliente (String Nombre, String Apellido, int Edad);
  boolean actualizarCliente (int id_cliente, String Nombre, String Apellido, int Edad);
  boolean eliminarCliente (int id_cliente);
  String consultarCliente (int id_cliente);
  void shoutdown ();
} // interface ClientesOperations
