package Cliente;


/**
* Cliente/ClientesHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cliente.idl
* viernes 16 de noviembre de 2018 21H54' COT
*/

abstract public class ClientesHelper
{
  private static String  _id = "IDL:Cliente/Clientes:1.0";

  public static void insert (org.omg.CORBA.Any a, Cliente.Clientes that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Cliente.Clientes extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Cliente.ClientesHelper.id (), "Clientes");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Cliente.Clientes read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ClientesStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Cliente.Clientes value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Cliente.Clientes narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Cliente.Clientes)
      return (Cliente.Clientes)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Cliente._ClientesStub stub = new Cliente._ClientesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Cliente.Clientes unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Cliente.Clientes)
      return (Cliente.Clientes)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Cliente._ClientesStub stub = new Cliente._ClientesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
