package Cliente;


/**
* Cliente/Clientes.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cliente.idl
* viernes 16 de noviembre de 2018 21H54' COT
*/

public interface Clientes extends ClientesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Clientes
