package Cliente;

/**
* Cliente/ClientesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cliente.idl
* viernes 16 de noviembre de 2018 21H54' COT
*/

public final class ClientesHolder implements org.omg.CORBA.portable.Streamable
{
  public Cliente.Clientes value = null;

  public ClientesHolder ()
  {
  }

  public ClientesHolder (Cliente.Clientes initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Cliente.ClientesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Cliente.ClientesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Cliente.ClientesHelper.type ();
  }

}
