package Factura;


/**
* Factura/FacturasOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Factura.idl
* domingo 18 de noviembre de 2018 04H59' COT
*/

public interface FacturasOperations 
{
  boolean insertarFactura (int id_cliente, int id_producto, int id_vendedor, String fecha, String matricula);
  boolean actualizarFactura (int id_factura, int id_cliente, int id_producto, int id_vendedor, String fecha, String matricula);
  boolean eliminarFactura (int id_factura);
  String consultarFactura (int id_factura);
  void shoutdown ();
} // interface FacturasOperations
