package Factura;


/**
* Factura/Facturas.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Factura.idl
* domingo 18 de noviembre de 2018 04H59' COT
*/

public interface Facturas extends FacturasOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Facturas
