module Producto{
    interface Productos{
    boolean insertarProducto(in wstring Nombre,in float Precio);
    boolean actualizarProducto(in long id_producto,in wstring Nombre,in float Precio);
    boolean eliminarProducto(in long id_producto);
    wstring consultarProducto(in long id_producto);
    
    oneway void shoutdown();
    };
    
};

