module Factura{
    interface Factura{
    boolean insertarFactura(in long id_cliente ,in long id_producto , in  long id_vendedor, in wstring fecha,in long id_vehiculo);
    boolean actualizarFactura(in long id_factura, in long id_cliente, in long id_producto , in long id_vendedor,in wstring fecha,in long id_vehiculo);
    boolean eliminarFactura(in long id_factura);
    wstring consultarFactura(in long id_factura);
    
    oneway void shoutdown();
    };
    
};

