module Vehiculo{
    interface Vehiculos{
    boolean insertarVehiculo( in wstring matricula,in  long id_domiciliario,in wstring marca);
    boolean actualizarVehiculo(in wstring matricula, in  long id_domiciliario, in wstring marca);
    boolean eliminarVehiculo(in wstring matricula);
    wstring consultarVehiculo(in wstring matricula);
    
    oneway void shoutdown();
    };
    
};

