module Vendedores{
    interface Vendedor{
    boolean insertarVendedor(in wstring Nombre,in long Telefono, in  long Cedula, in wstring Cargo);
    boolean actualizarVendedor(in long id_vendedor,in wstring Nombre,in long Telefono, in  long Cedula, in wstring Cargo);
    boolean eliminarVendedor(in long id_vendedor);
    wstring consultarVendedor(in long id_vendedor);
    
    oneway void shoutdown();
    };
    
};

