package Vehiculo;

/**
* Vehiculo/VehiculosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Vehiculo.idl
* domingo 18 de noviembre de 2018 02H56' COT
*/

public final class VehiculosHolder implements org.omg.CORBA.portable.Streamable
{
  public Vehiculo.Vehiculos value = null;

  public VehiculosHolder ()
  {
  }

  public VehiculosHolder (Vehiculo.Vehiculos initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Vehiculo.VehiculosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Vehiculo.VehiculosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Vehiculo.VehiculosHelper.type ();
  }

}
