package Vehiculo;


/**
* Vehiculo/Vehiculos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Vehiculo.idl
* domingo 18 de noviembre de 2018 02H56' COT
*/

public interface Vehiculos extends VehiculosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Vehiculos
