package Vehiculo;


/**
* Vehiculo/VehiculosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Vehiculo.idl
* domingo 18 de noviembre de 2018 02H56' COT
*/

public interface VehiculosOperations 
{
  boolean insertarVehiculo (String matricula, int id_domiciliario, String marca);
  boolean actualizarVehiculo (String matricula, int id_domiciliario, String marca);
  boolean eliminarVehiculo (String matricula);
  String consultarVehiculo (String matricula);
  void shoutdown ();
} // interface VehiculosOperations
